[package]
name = "rust-opentelemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
log = "0.4.26"
opentelemetry = "0.28.0"
opentelemetry-otlp = { version = "0.28.0", features = ["default"] }
opentelemetry_sdk = "0.28.0"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.29.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "registry"] }
