services:
  server:
    container_name: server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - metrics

  jaeger:
    image: jaegertracing/all-in-one:1.68.0
    container_name: jaeger
    restart: on-failure
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - metrics

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.5
    container_name: elasticsearch
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - metrics

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: on-failure
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3003:3000"
    expose:
      - 3003
    networks:
      - metrics
networks:
  metrics:

volumes:
  elasticsearch_data:
  prometheus_data:
    external: false
  grafana_data:
    external: false
