# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Configuration pour scraper votre application Rust
  - job_name: 'rust-app'
    static_configs:
      - targets: ['host.docker.internal:3333']  # Ajustez le port selon votre app
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Si vous utilisez l'OTEL Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']