global:
  scrape_interval:     30s
  evaluation_interval: 30s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'API'
    scrape_interval: 5s
#    basic_auth:
#      username: toto
#      password: toto
    static_configs:
      - targets: ['server:3333']
